import type { Action, OperationId } from '../engine/types';
import type { LevelId } from './levels';

function place(operationId: OperationId): Action {
  return Object.freeze({ type: 'place', operationId });
}

function wait(rank: number): Action {
  return Object.freeze({ type: 'wait', rank });
}

function placeIds(...operationIds: readonly OperationId[]): readonly Action[] {
  return Object.freeze(operationIds.map((operationId) => place(operationId)));
}

function withLeadingWait(actions: readonly Action[]): readonly Action[] {
  return Object.freeze([wait(0), ...actions]);
}

function stampedPatternActions(): readonly Action[] {
  return Object.freeze([
    place('F:0:0'),
    place('F:1:0'),
    place('B:1:0'),
    wait(0),
    wait(0),
    place('F:0:1'),
    place('B:0:0'),
    place('F:1:1'),
    place('B:1:1'),
    place('F:0:2'),
    place('B:0:1'),
    place('F:1:2'),
    place('B:1:2'),
    place('B:0:2'),
  ]);
}

const masteredActions = {
  'dependency-chain': placeIds('F:0:0', 'F:1:0', 'B:1:0', 'B:0:0'),
  'fill-the-pipe': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:1:1',
    'F:1:2',
    'B:1:0',
    'B:0:0',
    'B:1:1',
    'B:0:1',
    'B:1:2',
    'B:0:2',
  ),
  'backward-is-heavier': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:1:1',
    'F:1:2',
    'F:2:0',
    'F:2:1',
    'F:2:2',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'B:2:2',
    'B:1:2',
    'B:0:2',
  ),
  'memory-wall': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'F:0:3',
    'F:1:2',
    'F:2:1',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'F:1:3',
    'F:2:2',
    'B:2:2',
    'B:1:2',
    'B:0:2',
    'F:2:3',
    'B:2:3',
    'B:1:3',
    'B:0:3',
  ),
  'gpipe-afab': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:0:3',
    'F:1:0',
    'F:1:1',
    'F:1:2',
    'F:1:3',
    'F:2:0',
    'F:2:1',
    'F:2:2',
    'F:2:3',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'B:2:2',
    'B:1:2',
    'B:0:2',
    'B:2:3',
    'B:1:3',
    'B:0:3',
  ),
  'warm-up-then-alternate': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'F:0:3',
    'F:1:2',
    'F:2:1',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'F:1:3',
    'F:2:2',
    'B:2:2',
    'B:1:2',
    'B:0:2',
    'F:2:3',
    'B:2:3',
    'B:1:3',
    'B:0:3',
  ),
  'tie-at-the-frontier': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'B:1:0',
    'B:0:0',
    'F:0:2',
    'F:1:1',
    'B:1:1',
    'B:0:1',
    'F:0:3',
    'F:1:2',
    'B:1:2',
    'B:0:2',
    'F:1:3',
    'B:1:3',
    'B:0:3',
  ),
  'memory-capped-one-f-one-b': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'F:0:3',
    'F:1:2',
    'F:2:1',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'F:0:4',
    'F:1:3',
    'F:2:2',
    'B:2:2',
    'B:1:2',
    'B:0:2',
    'F:1:4',
    'F:2:3',
    'B:2:3',
    'B:1:3',
    'B:0:3',
    'F:2:4',
    'B:2:4',
    'B:1:4',
    'B:0:4',
  ),
  'stamp-the-pattern': stampedPatternActions(),
  'virtual-stages': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:2:0',
    'F:3:0',
    'B:3:0',
    'F:1:1',
    'F:2:1',
    'F:3:1',
    'B:3:1',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
  ),
  'interleaved-one-f-one-b': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:2:0',
    'F:3:0',
    'B:3:0',
    'F:1:1',
    'F:2:1',
    'F:3:1',
    'B:3:1',
    'F:0:2',
    'F:1:2',
    'F:2:2',
    'F:3:2',
    'B:3:2',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'B:2:2',
    'B:1:2',
    'B:0:2',
  ),
  'ragged-rounds': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:2:0',
    'F:3:0',
    'B:3:0',
    'F:1:1',
    'F:2:1',
    'F:3:1',
    'B:3:1',
    'F:0:2',
    'F:1:2',
    'F:2:2',
    'F:3:2',
    'B:3:2',
    'F:0:3',
    'F:1:3',
    'F:2:3',
    'F:3:3',
    'B:3:3',
    'F:0:4',
    'F:1:4',
    'F:2:4',
    'F:3:4',
    'B:3:4',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'B:2:2',
    'B:1:2',
    'B:0:2',
    'B:2:3',
    'B:1:3',
    'B:0:3',
    'B:2:4',
    'B:1:4',
    'B:0:4',
  ),
  'heavy-backward-tail': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:2:0',
    'F:3:0',
    'B:3:0',
    'F:1:1',
    'F:2:1',
    'F:3:1',
    'B:3:1',
    'F:0:2',
    'F:1:2',
    'F:2:2',
    'F:3:2',
    'B:3:2',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'B:2:1',
    'B:1:1',
    'B:0:1',
    'B:2:2',
    'B:1:2',
    'B:0:2',
  ),
  'split-backward': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'B:1:0',
    'B:0:0',
    'F:1:1',
    'W:0:0',
    'B:1:1',
    'B:0:1',
    'W:1:0',
    'W:0:1',
    'W:1:1',
  ),
  'zero-bubble-h1': placeIds(
    'F:0:0',
    'F:1:0',
    'F:0:1',
    'B:1:0',
    'F:0:2',
    'B:0:0',
    'F:1:1',
    'B:1:1',
    'W:0:0',
    'B:0:1',
    'F:1:2',
    'B:1:2',
    'W:0:1',
    'B:0:2',
    'W:1:0',
    'W:1:1',
    'W:0:2',
    'W:1:2',
  ),
  'zero-bubble-h2': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:1:0',
    'F:2:0',
    'F:1:1',
    'B:2:0',
    'F:1:2',
    'F:0:3',
    'B:1:0',
    'F:2:1',
    'B:0:0',
    'B:2:1',
    'F:1:3',
    'B:1:1',
    'F:2:2',
    'W:0:0',
    'B:0:1',
    'B:2:2',
    'W:1:0',
    'B:1:2',
    'F:2:3',
    'W:0:1',
    'B:0:2',
    'B:2:3',
    'W:1:1',
    'B:1:3',
    'W:2:0',
    'W:0:2',
    'B:0:3',
    'W:2:1',
    'W:1:2',
    'W:2:2',
    'W:1:3',
    'W:0:3',
    'W:2:3',
  ),
  'zero-bubble-deep': placeIds(
    'F:0:0',
    'F:0:1',
    'F:0:2',
    'F:0:3',
    'F:0:4',
    'F:1:0',
    'F:2:0',
    'F:1:1',
    'F:3:0',
    'F:2:1',
    'F:1:2',
    'B:3:0',
    'F:2:2',
    'F:1:3',
    'B:2:0',
    'F:3:1',
    'F:1:4',
    'B:1:0',
    'B:3:1',
    'F:2:3',
    'B:0:0',
    'B:2:1',
    'F:3:2',
    'W:1:0',
    'B:1:1',
    'B:3:2',
    'F:2:4',
    'W:0:0',
    'B:0:1',
    'B:2:2',
    'F:3:3',
    'W:1:1',
    'B:1:2',
    'B:3:3',
    'W:2:0',
    'W:0:1',
    'B:0:2',
    'B:2:3',
    'F:3:4',
    'W:1:2',
    'B:1:3',
    'B:3:4',
    'W:2:1',
    'W:0:2',
    'B:0:3',
    'B:2:4',
    'W:3:0',
    'W:1:3',
    'B:1:4',
    'W:3:1',
    'W:2:2',
    'W:0:3',
    'B:0:4',
    'W:3:2',
    'W:2:3',
    'W:1:4',
    'W:3:3',
    'W:2:4',
    'W:0:4',
    'W:3:4',
  ),
  'group-the-pipe': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'F:2:1',
    'B:2:0',
    'B:2:1',
    'B:1:0',
    'B:1:1',
    'B:0:0',
    'B:0:1',
    'F:0:2',
    'F:0:3',
    'F:1:2',
    'F:1:3',
    'F:2:2',
    'F:2:3',
    'B:2:2',
    'B:2:3',
    'B:1:2',
    'B:1:3',
    'B:0:2',
    'B:0:3',
  ),
  'bf-pp-pressure': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'F:2:1',
    'B:2:0',
    'B:2:1',
    'B:1:0',
    'B:1:1',
    'B:0:0',
    'B:0:1',
    'F:0:2',
    'F:0:3',
    'F:1:2',
    'F:1:3',
    'F:2:2',
    'F:2:3',
    'B:2:2',
    'B:2:3',
    'B:1:2',
    'B:1:3',
    'B:0:2',
    'B:0:3',
    'F:0:4',
    'F:0:5',
    'F:1:4',
    'F:1:5',
    'F:2:4',
    'F:2:5',
    'B:2:4',
    'B:2:5',
    'B:1:4',
    'B:1:5',
    'B:0:4',
    'B:0:5',
  ),
  'gather-once-reuse': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'B:1:0',
    'B:0:0',
    'F:1:1',
    'B:1:1',
    'B:0:1',
  ),
  'group-too-wide': placeIds(
    'F:0:0',
    'F:1:0',
    'F:2:0',
    'F:3:0',
    'B:3:0',
    'B:2:0',
    'B:1:0',
    'B:0:0',
    'F:0:1',
    'F:1:1',
    'F:2:1',
    'F:3:1',
    'B:3:1',
    'B:2:1',
    'B:1:1',
    'B:0:1',
  ),
  'regather-storm': placeIds(
    'F:0:0',
    'F:0:1',
    'F:1:0',
    'F:1:1',
    'F:2:0',
    'F:2:1',
    'F:3:0',
    'F:3:1',
    'B:3:0',
    'B:3:1',
    'B:2:0',
    'B:2:1',
    'B:1:0',
    'B:1:1',
    'B:0:0',
    'B:0:1',
    'F:0:2',
    'F:0:3',
    'F:1:2',
    'F:1:3',
    'F:2:2',
    'F:2:3',
    'F:3:2',
    'F:3:3',
    'B:3:2',
    'B:3:3',
    'B:2:2',
    'B:2:3',
    'B:1:2',
    'B:1:3',
    'B:0:2',
    'B:0:3',
  ),
  'two-directions': placeIds(
    'F:0:0:asc',
    'F:1:0:desc',
    'F:0:0:desc',
    'F:1:0:asc',
    'B:0:0:desc',
    'B:1:0:asc',
    'B:0:0:asc',
    'B:1:0:desc',
  ),
  'dualpipe-balance': placeIds(
    'F:0:0:asc',
    'F:1:0:desc',
    'F:0:0:desc',
    'F:1:0:asc',
    'F:0:1:asc',
    'F:1:1:desc',
    'F:0:1:desc',
    'F:1:1:asc',
    'B:0:0:desc',
    'B:1:0:asc',
    'B:0:0:asc',
    'B:1:0:desc',
    'B:0:1:desc',
    'B:1:1:asc',
    'B:0:1:asc',
    'B:1:1:desc',
  ),
  'dualpipe-conflict': placeIds(
    'F:0:0:asc',
    'F:1:0:desc',
    'F:0:0:desc',
    'F:1:0:asc',
    'F:0:1:asc',
    'F:1:1:desc',
    'F:0:1:desc',
    'F:1:1:asc',
    'B:0:0:desc',
    'B:1:0:asc',
    'B:0:0:asc',
    'B:1:0:desc',
    'B:0:1:desc',
    'B:1:1:asc',
    'B:0:1:asc',
    'B:1:1:desc',
  ),
} satisfies Record<LevelId, readonly Action[]>;

export const MASTERED_ACTIONS = Object.freeze(masteredActions);

const legalActions = {
  'dependency-chain': withLeadingWait(MASTERED_ACTIONS['dependency-chain']),
  'fill-the-pipe': withLeadingWait(MASTERED_ACTIONS['fill-the-pipe']),
  'backward-is-heavier': withLeadingWait(MASTERED_ACTIONS['backward-is-heavier']),
  'memory-wall': withLeadingWait(MASTERED_ACTIONS['memory-wall']),
  'gpipe-afab': withLeadingWait(MASTERED_ACTIONS['gpipe-afab']),
  'warm-up-then-alternate': withLeadingWait(MASTERED_ACTIONS['warm-up-then-alternate']),
  'tie-at-the-frontier': withLeadingWait(MASTERED_ACTIONS['tie-at-the-frontier']),
  'memory-capped-one-f-one-b': withLeadingWait(MASTERED_ACTIONS['memory-capped-one-f-one-b']),
  'stamp-the-pattern': withLeadingWait(MASTERED_ACTIONS['stamp-the-pattern']),
  'virtual-stages': withLeadingWait(MASTERED_ACTIONS['virtual-stages']),
  'interleaved-one-f-one-b': withLeadingWait(MASTERED_ACTIONS['interleaved-one-f-one-b']),
  'ragged-rounds': withLeadingWait(MASTERED_ACTIONS['ragged-rounds']),
  'heavy-backward-tail': withLeadingWait(MASTERED_ACTIONS['heavy-backward-tail']),
  'split-backward': withLeadingWait(MASTERED_ACTIONS['split-backward']),
  'zero-bubble-h1': withLeadingWait(MASTERED_ACTIONS['zero-bubble-h1']),
  'zero-bubble-h2': withLeadingWait(MASTERED_ACTIONS['zero-bubble-h2']),
  'zero-bubble-deep': withLeadingWait(MASTERED_ACTIONS['zero-bubble-deep']),
  'group-the-pipe': withLeadingWait(MASTERED_ACTIONS['group-the-pipe']),
  'bf-pp-pressure': withLeadingWait(MASTERED_ACTIONS['bf-pp-pressure']),
  'gather-once-reuse': withLeadingWait(MASTERED_ACTIONS['gather-once-reuse']),
  'group-too-wide': withLeadingWait(MASTERED_ACTIONS['group-too-wide']),
  'regather-storm': withLeadingWait(MASTERED_ACTIONS['regather-storm']),
  'two-directions': withLeadingWait(MASTERED_ACTIONS['two-directions']),
  'dualpipe-balance': withLeadingWait(MASTERED_ACTIONS['dualpipe-balance']),
  'dualpipe-conflict': withLeadingWait(MASTERED_ACTIONS['dualpipe-conflict']),
} satisfies Record<LevelId, readonly Action[]>;

export const LEGAL_ACTIONS = Object.freeze(legalActions);
